import Head from 'next/head'
import React from 'react'
import ContactForm from '../components/ContactForm'
import Section from '../components/Section'
import Title from '../components/Title'

const contact = () => {
  return (
    <>
    <Head>
      <title>コンタクト : Meidaimae no Aogakusei</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Section>
      <Title name="Contact"/>
      <ContactForm />
    </Section>

  </>
  )
}

export default contact