import Head from 'next/head'
import React from 'react'

const contact = () => {
  return (
    <>
    <Head>
      <title>コンタクト</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

  </>
  )
}

export default contact